USE [master]
GO
/****** Object:  Database [Sample_Db]    Script Date: 4/10/2019 4:54:33 PM ******/
CREATE DATABASE [Sample_Db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sample_Db', FILENAME = N'C:\Sample_Db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sample_Db_log', FILENAME = N'C:\Sample_Db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Sample_Db] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sample_Db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Sample_Db] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Sample_Db] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Sample_Db] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Sample_Db] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Sample_Db] SET ARITHABORT OFF 
GO
ALTER DATABASE [Sample_Db] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Sample_Db] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Sample_Db] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Sample_Db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Sample_Db] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Sample_Db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Sample_Db] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Sample_Db] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Sample_Db] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Sample_Db] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Sample_Db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Sample_Db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Sample_Db] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Sample_Db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Sample_Db] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Sample_Db] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Sample_Db] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Sample_Db] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Sample_Db] SET  MULTI_USER 
GO
ALTER DATABASE [Sample_Db] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Sample_Db] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Sample_Db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Sample_Db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Sample_Db] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Sample_Db] SET QUERY_STORE = OFF
GO
USE [Sample_Db]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Sample_Db]
GO
/****** Object:  Table [dbo].[Customer_Master]    Script Date: 4/10/2019 4:54:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer_Master](
	[Customer_ID] [int] IDENTITY(1,1) NOT NULL,
	[Customer_Code] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Customer_Master] PRIMARY KEY CLUSTERED 
(
	[Customer_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Frequency_Master]    Script Date: 4/10/2019 4:54:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Frequency_Master](
	[Frequency_ID] [int] IDENTITY(1,1) NOT NULL,
	[Frequency_Code] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Frequency_Master] PRIMARY KEY CLUSTERED 
(
	[Frequency_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Usecase_Master]    Script Date: 4/10/2019 4:54:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usecase_Master](
	[Usecase_ID] [int] IDENTITY(1,1) NOT NULL,
	[Usecase_Code] [varchar](30) NOT NULL,
 CONSTRAINT [PK_Usecase_Master] PRIMARY KEY CLUSTERED 
(
	[Usecase_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET IDENTITY_INSERT [dbo].[Customer_Master] ON 

GO
INSERT [dbo].[Customer_Master] ([Customer_ID], [Customer_Code]) VALUES (1, N'Customer_1')
GO
INSERT [dbo].[Customer_Master] ([Customer_ID], [Customer_Code]) VALUES (2, N'Customer_2')
GO
INSERT [dbo].[Customer_Master] ([Customer_ID], [Customer_Code]) VALUES (3, N'Customer_3')
GO
INSERT [dbo].[Customer_Master] ([Customer_ID], [Customer_Code]) VALUES (4, N'Customer_4')
GO
INSERT [dbo].[Customer_Master] ([Customer_ID], [Customer_Code]) VALUES (5, N'Customer_5')
GO
SET IDENTITY_INSERT [dbo].[Customer_Master] OFF
GO
SET IDENTITY_INSERT [dbo].[Frequency_Master] ON 

GO
INSERT [dbo].[Frequency_Master] ([Frequency_ID], [Frequency_Code]) VALUES (1, N'Hourly')
GO
INSERT [dbo].[Frequency_Master] ([Frequency_ID], [Frequency_Code]) VALUES (2, N'Daily')
GO
INSERT [dbo].[Frequency_Master] ([Frequency_ID], [Frequency_Code]) VALUES (3, N'Weekly')
GO
INSERT [dbo].[Frequency_Master] ([Frequency_ID], [Frequency_Code]) VALUES (4, N'Monthly')
GO
SET IDENTITY_INSERT [dbo].[Frequency_Master] OFF
GO
SET IDENTITY_INSERT [dbo].[Usecase_Master] ON 

GO
INSERT [dbo].[Usecase_Master] ([Usecase_ID], [Usecase_Code]) VALUES (1, N'Usecase_1')
GO
INSERT [dbo].[Usecase_Master] ([Usecase_ID], [Usecase_Code]) VALUES (2, N'Usecase_2')
GO
INSERT [dbo].[Usecase_Master] ([Usecase_ID], [Usecase_Code]) VALUES (3, N'Usecase_3')
GO
INSERT [dbo].[Usecase_Master] ([Usecase_ID], [Usecase_Code]) VALUES (4, N'Usecase_4')
GO
INSERT [dbo].[Usecase_Master] ([Usecase_ID], [Usecase_Code]) VALUES (5, N'Usecase_5')
GO
SET IDENTITY_INSERT [dbo].[Usecase_Master] OFF
GO
USE [master]
GO
ALTER DATABASE [Sample_Db] SET  READ_WRITE 
GO
